//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC15TwitterEventKitP33_508546FD4F868D248CF5557BEF798F1626ComponentCollectionSession : _TtCs12_SwiftObject
{
    // Error parsing type: , name: viewBuilder
    // Error parsing type: , name: eventBlocked
}

@end

