//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC15TwitterEventKit13EventPipelineP33_EA0DB4C492E1AE13D7864AD9F56561EE19EventImpressionData : _TtCs12_SwiftObject
{
    // Error parsing type: , name: view
    // Error parsing type: , name: viewPath
}

@end

