//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNCollectionViewCell.h>

@class TFNDataViewCellLayout;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter23TopicCollectionItemCell : TFNCollectionViewCell
{
    // Error parsing type: , name: name
    // Error parsing type: , name: isFollowing
    // Error parsing type: , name: roundedCornerView
    // Error parsing type: , name: roundedBorderView
    // Error parsing type: , name: nameView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: imageName
}

- (void).cxx_destruct;
@property(nonatomic, retain) TFNDataViewCellLayout *cellLayout;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

