//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC15TwitterEventKit22EventComponentRegistryP33_1BF4C30ACA2BB5483BE71F5E54DD3C5018ConcurrentRegistry : _TtCs12_SwiftObject
{
    // Error parsing type: , name: registry
    // Error parsing type: , name: unfairAccessLock
}

@end

