//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNTableViewCell.h>

@class UIColor, UILabel, UIStackView, UITapGestureRecognizer, UIView;

@interface T1NudgeItemCell : TFNTableViewCell
{
    _Bool _contextViewShouldFillWidth;
    double _contentVerticalSpacing;
    UIColor *_nudgeBackgroundColor;
    UIView *_iconView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIView *_contextView;
    CDUnknownBlockType _contextAction;
    UIView *_nudgeContainerView;
    UIStackView *_expandedStackView;
    UITapGestureRecognizer *_contextViewTapGesture;
    struct UIEdgeInsets _contentEdgeInsets;
    struct UIEdgeInsets _containerEdgeInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *contextViewTapGesture; // @synthesize contextViewTapGesture=_contextViewTapGesture;
@property(readonly, nonatomic) struct UIEdgeInsets containerEdgeInsets; // @synthesize containerEdgeInsets=_containerEdgeInsets;
@property(readonly, nonatomic) struct UIEdgeInsets contentEdgeInsets; // @synthesize contentEdgeInsets=_contentEdgeInsets;
@property(retain, nonatomic) UIStackView *expandedStackView; // @synthesize expandedStackView=_expandedStackView;
@property(retain, nonatomic) UIView *nudgeContainerView; // @synthesize nudgeContainerView=_nudgeContainerView;
@property(copy, nonatomic) CDUnknownBlockType contextAction; // @synthesize contextAction=_contextAction;
@property(retain, nonatomic) UIView *contextView; // @synthesize contextView=_contextView;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIColor *nudgeBackgroundColor; // @synthesize nudgeBackgroundColor=_nudgeBackgroundColor;
@property(nonatomic) _Bool contextViewShouldFillWidth; // @synthesize contextViewShouldFillWidth=_contextViewShouldFillWidth;
@property(nonatomic) double contentVerticalSpacing; // @synthesize contentVerticalSpacing=_contentVerticalSpacing;
- (void)_t1_setArrangedSubviews;
- (void)_t1_contextViewTapped:(id)arg1;
- (double)_t1_labelPreferredMaxLayoutWidthForSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)_t1_addAndConstrainSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

