//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNLegacyButton.h>

@class TFNTwitterUnifiedCardButtonData;

@interface T1UnifiedCardButton : TFNLegacyButton
{
    TFNTwitterUnifiedCardButtonData *_dataModel;
}

+ (struct CGSize)sizeForDataModel:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) TFNTwitterUnifiedCardButtonData *dataModel; // @synthesize dataModel=_dataModel;
- (void)_t1_configureButtonWithDominantColorConfig:(id)arg1 strength:(unsigned long long)arg2;
- (void)_t1_updateContentFromDataModel;
- (void)updateWithDataModel:(id)arg1;
- (id)initWithDataModel:(id)arg1 dominantColorConfig:(id)arg2;

@end

