//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSString, T1UserBadge, T1VoiceStatusViewModel, TFSTwitterEntityMedia;

@interface T1VoiceDockStatusViewModel : NSObject
{
    double _totalDuration;
    double _previousDuration;
    T1VoiceStatusViewModel *_voiceViewModel;
    T1UserBadge *_userBadge;
}

+ (id)new;
- (void).cxx_destruct;
@property(readonly, nonatomic) T1UserBadge *userBadge; // @synthesize userBadge=_userBadge;
@property(readonly, nonatomic) T1VoiceStatusViewModel *voiceViewModel; // @synthesize voiceViewModel=_voiceViewModel;
@property(readonly, nonatomic) double previousDuration; // @synthesize previousDuration=_previousDuration;
- (id)_t1_accessibleDurationRemainingStringWithProgress:(double)arg1;
- (id)_t1_durationStringWithProgress:(double)arg1;
- (id)_t1_badgeAttributedStringWithFont:(id)arg1;
- (_Bool)isEqualToViewModel:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)player;
- (id)accessibilityStringCurrentlyPlaying:(_Bool)arg1 withProgress:(double)arg2;
@property(readonly, nonatomic) NSAttributedString *subtitleAttributedString;
- (id)titleAttributedStringWithProgress:(double)arg1;
@property(readonly, nonatomic) TFSTwitterEntityMedia *imageMediaEntity;
@property(readonly, nonatomic) NSString *imageName;
@property(readonly, nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
- (id)initWithVoiceViewModel:(id)arg1 previousDuration:(double)arg2 totalDuration:(double)arg3;
- (id)init;

@end

