//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, TFNTwitterUnifiedCardDestinationModel;

@interface TFNTwitterUnifiedCardButtonData : NSObject
{
    _Bool _useDominantColor;
    NSString *_title;
    NSNumber *_iconType;
    TFNTwitterUnifiedCardDestinationModel *_destination;
    unsigned long long _buttonVariation;
    unsigned long long _strength;
    unsigned long long _variant;
    unsigned long long _size;
}

+ (id)fileNameForIconType:(long long)arg1;
+ (unsigned long long)_tfn_strengthForCTAButtonVariation:(unsigned long long)arg1;
+ (unsigned long long)_tfn_sizeForCTAButtonVariation:(unsigned long long)arg1;
+ (unsigned long long)_tfn_variantForCTAButtonVariation:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool useDominantColor; // @synthesize useDominantColor=_useDominantColor;
@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
@property(readonly, nonatomic) unsigned long long variant; // @synthesize variant=_variant;
@property(readonly, nonatomic) unsigned long long strength; // @synthesize strength=_strength;
@property(nonatomic) unsigned long long buttonVariation; // @synthesize buttonVariation=_buttonVariation;
@property(readonly, nonatomic) TFNTwitterUnifiedCardDestinationModel *destination; // @synthesize destination=_destination;
@property(readonly, nonatomic) NSNumber *iconType; // @synthesize iconType=_iconType;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDestination:(id)arg1 iconType:(id)arg2 title:(id)arg3 strength:(unsigned long long)arg4 variant:(unsigned long long)arg5 size:(unsigned long long)arg6 useDominantColor:(_Bool)arg7;
- (id)initWithButtonDictionary:(id)arg1 destinationDictionary:(id)arg2;
- (id)buttonDataWithCTAButtonVariation:(unsigned long long)arg1;

@end

