//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterEventKit/TREKEventPipeline.h>

#import <TwitterEventKit/EventProcessingPipelineProtocol-Protocol.h>

@interface TREKEventPipeline (TwitterEventKit) <EventProcessingPipelineProtocol>
- (void)handleTapEvent:(id)arg1 tapCount:(long long)arg2 touchCount:(long long)arg3;
- (void)handlePullToRefreshEvent:(id)arg1;
- (void)handleScrollEvent:(id)arg1 direction:(int)arg2;
- (void)handleSwipeEvent:(id)arg1 direction:(int)arg2;
@end

